### ISSUE TITLE
Collection setting addition to weekly logs

### ISSUE THREAD

**Issue by kmazzilli** [Analyticsphere/metricsReportsRequests#75] opened 2023-10-18 20:54 UTC
Requestor(s): Kaitlyn Mazzilli and Amelia Roberts

Metrics to be updated or created: Weekly Logs

Notes: We would like to add 2 columns to the weekly logs to distinguish the collection setting (for the overall logs and the site specific). "Number of Clinical Samples Collected" and "Number of Research Samples Collected". Some of the sites may have 0 total for either column depending on what setting they offer.

Approved by: Michelle Brotzman

**Comment by KELSEYDOWLING7** [comment] 2023-10-19 15:05
@kmazzilli @robertsamm  Good morning, please see the logs attached. For some reason the box is left blank instead of 0 if there are no collections of that setting type. Please let me know if this will suffice.

Also please disregard the date, I forgot to run one line of code to update that to today's date


[CCC_metrics_weekly_log_labels_Kaiser Permanente Hawaii2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044262/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Hawaii2023-10-17.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Northwest2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044263/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Northwest2023-10-17.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Colorado2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044264/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Colorado2023-10-17.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Georgia2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044265/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Georgia2023-10-17.csv)
[CCC_metrics_weekly_log_labels_University of Chicago Medicine2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044266/CCC_metrics_weekly_log_labels_University.of.Chicago.Medicine2023-10-17.csv)
[CCC_metrics_weekly_log_labels_Sanford Health2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044267/CCC_metrics_weekly_log_labels_Sanford.Health2023-10-17.csv)
[CCC_metrics_weekly_log_labels_Marshfield Clinic Health System2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044268/CCC_metrics_weekly_log_labels_Marshfield.Clinic.Health.System2023-10-17.csv)
[CCC_metrics_weekly_log_labels_Henry Ford Health System2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044269/CCC_metrics_weekly_log_labels_Henry.Ford.Health.System2023-10-17.csv)
[CCC_metrics_weekly_log_labels_HealthPartners2023-10-17.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13044270/CCC_metrics_weekly_log_labels_HealthPartners2023-10-17.csv)

**Comment by brotzmanmj** [comment] 2023-10-19 15:39
These look great to me, happy to have these data. Added Domonique so she's in the loop too. About having blank instead of zero, I think that's ok but wanted to check with Domonique, if we run graphics in Excel off these tables the way you sometimes do, if they are blank does it just assume they are 0?

**Comment by kmazzilli** [comment] 2023-10-19 15:49
@KELSEYDOWLING7 thanks for getting to this so quickly. Amelia and I took a look and have some additional feedback:

1. We would like to get 0's if possible instead of blanks.
2. Can the labels instead read "Number of clinical samples collected per week" and "Number of research samples collected per week"
3.  We also think it would be helpful to add two additional columns for the cumulative counts, "Cumulative number of clinical samples collected per week" and "Cumulative number of research samples collected per week"
4. Can these four columns be placed in between "Specimens collected per week" and "Cumulative All Baseline Surveys (Modules 1-4)"?
5.  I see files for all the sites in your last comment, but would like to confirm that the overall/all site log will be updated as well
6.  Lastly, the logs shouldn't include a week that hasn't happened yet/still in progress, so the week of 10/16-10/22 should be removed, and this exclusion should apply to all future weeks. 

Thanks again!

**Comment by HopkinsDC** [comment] 2023-10-19 15:55
I confirm that the blanks in the last two columns indicate no collections for those weeks; these should be 0, as Kaitlyn and Amelia suggested above.

I also suggest that "Number of research collections per week" and "Number of clinical collections per week" be used as the title for those columns; using "samples" implies individual tubes rather than the whole collection.

**Comment by KELSEYDOWLING7** [comment] 2023-10-19 16:43
@kmazzilli  @HopkinsDC  All set! yes, the overall csv will be updated as well. That one is giving me more trouble, so I figured I would post just the site CSVs for now and update the Overall as we finalize all the changes. Please see the site csv's below with the updated request


[CCC_metrics_weekly_log_labels_HealthPartners2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045376/CCC_metrics_weekly_log_labels_HealthPartners2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Henry Ford Health System2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045377/CCC_metrics_weekly_log_labels_Henry.Ford.Health.System2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Colorado2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045378/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Colorado2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Georgia2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045379/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Georgia2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Hawaii2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045380/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Hawaii2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Kaiser Permanente Northwest2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045381/CCC_metrics_weekly_log_labels_Kaiser.Permanente.Northwest2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Marshfield Clinic Health System2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045382/CCC_metrics_weekly_log_labels_Marshfield.Clinic.Health.System2023-10-19.csv)
[CCC_metrics_weekly_log_labels_Sanford Health2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045383/CCC_metrics_weekly_log_labels_Sanford.Health2023-10-19.csv)
[CCC_metrics_weekly_log_labels_University of Chicago Medicine2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045384/CCC_metrics_weekly_log_labels_University.of.Chicago.Medicine2023-10-19.csv)

**Comment by KELSEYDOWLING7** [comment] 2023-10-19 17:42
@kmazzilli Here is the final overall as well

[CCC_metrics_weekly_log_labels_2023-10-19.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/13045951/CCC_metrics_weekly_log_labels_2023-10-19.csv)

**Comment by kmazzilli** [comment] 2023-10-19 21:06
Great @KELSEYDOWLING7. There are just some typos in the headers, for example on the ones we just requested, they say "Cummulative", could you do a double check? Thanks!

**Comment by KELSEYDOWLING7** [comment] 2023-10-20 12:15
@kmazzilli  All set! Please let me know if there are any others. Jake can push these changes when we meet this afternoon for Mondays report if they're ready.


Also general question. Are there any pending changes that have been approved for the DCEG version of this report but not the Connect ALL version? I'd very much like to avoid multiple versions of the code to avoid issues down the line, and that way Jake can have both reports automatically pushed to Box as opposed to one manual upload (Connect ALL) and one automatic upload.

**Comment by robertsamm** [comment] 2023-10-20 12:38
Good morning @KELSEYDOWLING7 I didn't see any other spelling errors besides the double m's in 'cumulative', I have just one more comment. Thanks for adding the cumulative number of research/clinical collections column. For those 2 cumulative labels can you take out the 'per week' at the end? 'Per week' should only be on the two prior that show the counts only for that given week.

The Weekly Logs are never posted to ALL, just the DCEG folder. Have then been getting posted to ALL too or are you thinking of the Weekly Operations Report?

**Comment by KELSEYDOWLING7** [comment] 2023-10-20 12:47
@robertsamm  Oh that makes sense, yes I can remove the 'per week' really quick. 

And yes, sorry I should have specified, the weekly Operations report is what I was referring to. The report and the logs use the same code file.

**Comment by robertsamm** [comment] 2023-10-20 12:53
So from my understanding, the automated code for the Operations Report should just go to ALL and should only contain whatever the latest approved code is and will be run on that weekly basis on Mondays. The DCEG folder for the operations report should only be posted in for when we are working on changes to the report/code so would be manually posted and will just contain draft versions of the operations report. Once the changes in DCEG are approved then they are loaded to the automated code for ALL. I don't think we need copies of the same clean report posted in ALL and DCEG on a weekly basis, our team can just look at the report in ALL for that. Although, maybe @brotzmanmj or @FrogGirl1123 should confirm this because my understanding could be incorrect!

The idea being, we don't want the sites to be able to see draft versions that are still being worked on in ALL which is why we work on them in DCEG first.

**Comment by KELSEYDOWLING7** [comment] 2023-10-20 12:59
@robertsamm Ah ok that makes sense, thank you. That's not how it's working currently so that's very good to know moving forward.

@brotzmanmj  Could I propose we change this  to the way we have the Biospecimen reports running now? Only the report with all approved changes will go to the ALL folder, and I will have Jake push that automatically. Instead of posting a full report for each individual change, I can post screenshots of the specific table or plot that is being requested to be changed or added, as well as post the output files that are being changed here.

**Comment by robertsamm** [comment] 2023-10-20 13:24
Hi @KELSEYDOWLING7, we like that idea and are good with switching to the same work flow you are doing with the biospecimen report. Thanks for suggesting!

**Comment by KELSEYDOWLING7** [comment] 2023-10-20 13:29
@robertsamm  Great, thank you! I'll let Jake know about the automation adjustment and that's helpful more me to keep track of all the report outputs in Box.


Are there any pending changes in the DCEG folder report that are not approved to be pushed to the ALL folder? I'm thinking the current DCEG report code should be ok to just start pushing to the ALL folder instead. It looks like most all the requests in open issues have been resolved: (and please correct me if I'm wrong or if changes requested on that Github issue are still needed)
#73  Footnote removed
#69 table updates approved
#67 The s is removed in "Figures" to "Figure". X axis dates are being addressed in open issue #74 
#66  legend title removed
#74  legend colors changed, x-axis labels/date range still pending





Looking side by side the only difference I saw was the figures 5.0-5.9 were in the DCEG test report and not in the ALL folder

**Comment by robertsamm** [comment] 2023-10-25 14:02
Hi @KELSEYDOWLING7, it looks like the collection setting column counts weren't in the latest weekly logs ran on 10/25. Are these going to be in the automation/prod report by Monday next week?

**Comment by KELSEYDOWLING7** [comment] 2023-10-25 14:14
@robertsamm They can be yes. I didn't want to merge my code changes into Jake's automated code just yet until I had confirmation that all pending changes were approved.

As it stands right now, I'd instead have to send these select edits to Jing, and have her merge that with Jake's current automation.

Please let me know if Figures 5.0-5.12 are ready for approval. If they are, I can simply get Jing's edits from the Figure 4 issues today, put everything into the automation, and remove the DCEG automation link altogether.

**Comment by robertsamm** [comment] 2023-10-25 14:16
@KELSEYDOWLING7 Hi Kelsey, I just confirmed with @kmazzilli that figures 5-5.12 look good and are ready to go in the automation/ALL. In the future, let's make sure we are keeping discussions of reports/figures to the correct github issue when there are multiple open

**Comment by KELSEYDOWLING7** [comment] 2023-10-25 14:17
@robertsamm  Couldn't agree more!

**Comment by robertsamm** [comment] 2023-10-25 14:20
@KELSEYDOWLING7 once they are all in the automation and uploaded to ALL (I'm assuming that will happen on Monday?) can you let us know so we can close out all the open issues?

**Comment by KELSEYDOWLING7** [comment] 2023-10-25 14:22
@robertsamm  Absolutely!

**Closed as completed** 2023-11-03 12:15 UTC
Labels: Needed but not urgent
