### ISSUE TITLE
Issue in Operations Report Related to Metrics for Data Destruction 

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#137] opened 2024-04-09 16:05 UTC
Hi @KELSEYDOWLING7 I was looking at the latest Operations Report (ran on 4/8) and focusing on the metrics related to data destruction now that the automated data destruction process has run in prod. Comparing to the 4/1 report, it looks like the metrics for Data Destruction are all missing data, but they should still have the data as we retained as part of the stub record the vars related to DD such as 'requested data destruction', 'date/time requested data destruction', 'reason for r/w', 'consented', and 'date/time' consented. 

Can you please look into why these metrics are missing the counts/metrics for those with a destroyed data status? Jing ran her code to look at the stub record at the time the data was destroyed and she was able to find that the stub vars were retained as expected. See below for more specific comments.

**Figure 5.0-5.9 - Weekly Counts**
Missing data destruction counts. Assuming the couple of counts on the figure in 4/8 are for people who requested data destruction but do not yet have their data destroyed. It should be showing all data destruction counts, regardless of destroyed data.
NEW 4/8 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/53ce7e1b-ffef-457b-b0e8-1db5f738db62)
OLD 4/1 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/35e51203-a3dc-4cfb-9fb9-537da0d619db)

**Figure 5.10-5.12 Cumulative Time Trend**
Missing orange data destruction count line and light blue data destruction per 1k line has gone to zero. Should still have both counts.
NEW 4/8 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/12e71be7-8ef9-4d48-ad07-b29c967b2c0f)
OLD 4/1 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/285b8272-3b15-45be-8b80-526649cd1610)

**Table 34 - Refusals and Withdrawals**
Data destruction requested counts have gone to zero and/or low numbers. Should be counting everyone who requested DD, regardless of whether their data has been destroyed.
NEW 4/8 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/68f6d150-bd82-4fed-82d6-dcd3b56aaa5d)
OLD 4/1 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/376932c5-1097-4609-a44b-96b1aedefde0)

**Table 35 - Reasons for R/W**
The count of reasons went down, but we are retaining reasons for withdrawal and data destruction in the stub record so should have remained.
NEW 4/8 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/ec0dbbe9-391c-427f-be15-3110e91dd7bc)
OLD 4/1 report:
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/4a5be202-6824-46de-96d1-dd26a61e4091)

**Comment by robertsamm** [comment] 2024-04-09 16:17
@KELSEYDOWLING7 Michelle suggested checking to see if these metrics are using the participation status variable or the individual flags for refusal/withdrawal/destruction? Once the data has been destroyed for a participant, the participation status for those individuals goes from '5=data destruction requested' to '6=Data Destroyed'. The metrics should be hinging off the individual flags for r/w status instead of participation status which may change.

**Comment by KELSEYDOWLING7** [comment] 2024-04-10 20:32
@robertsamm  Thank you for letting me know!  It looks like the issue is  a majority of the report had a dependency on recruitment status, and when that was remove with DD, those counts went with it. 

With Jing's help Figures 5.0, 5.10-5.12 are back to their normal counts. 

For Table 34, part of that dependency was on the sign in flag=yes, which was deleted. So we replaced that with sign in  flag=yes OR consent flag=yes and we got the counts back for the Data Destructions requests. All other counts remained the same with that conditionality change.

Table 35 is more complicated and we're still working on it.

**Comment by KELSEYDOWLING7** [comment] 2024-04-10 20:57
@robertsamm  Upon further review, the reasons for refusal or withdrawal were not saved as intended. The reason d_919699172 ("I am no longer interested in the study") is the only reason with data saved. All other reasons response were deleted for every participant who had their data destroyed. This is the case in the raw and flattened data in BQ

**Comment by robertsamm** [comment] 2024-04-11 12:19
Good morning @KELSEYDOWLING7, thanks for looking into this issue. I'm tagging @brotzmanmj for her awareness. Michelle, it looks like not all 'reasons for r/w' are being retained in the stub record. See above.

**Comment by brotzmanmj** [comment] 2024-04-11 12:57
@KELSEYDOWLING7 I'm opening a ticket in GitHub for this and assigning to Jessica, thanks for the heads up

**Comment by KELSEYDOWLING7** [comment] 2024-04-11 14:44
@robertsamm  The remaining issues outside of that are fixed. And table 34's fix added back to Table 35 those that had data destruction but answered d_919699172 ("I am no longer interested in the study") 

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d5c17976-6d85-4f5c-b76e-255cba865982)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/796278cb-281c-4245-99dc-73882d9b42f3)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6d7c68c7-97e6-4754-a9ed-7dcc753860b9)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/64bedf94-dbf6-4a6f-a967-a5c693d66cf5)

**Comment by robertsamm** [comment] 2024-04-11 14:48
Thanks @KELSEYDOWLING7 for making these fixes with Jing! All the updated figures above look good now.

**Comment by brotzmanmj** [comment] 2024-04-11 14:51
Thank to you all! Can you convey this information in the GitHub ticket I created for Jessica and then close it?

**Comment by robertsamm** [comment] 2024-04-11 14:53
@brotzmanmj there is still the issue with the reasons for r/w so I think that ticket for Jessica needs to remain open

**Comment by brotzmanmj** [comment] 2024-04-11 14:53
Oh thanks, I was conflating the two

**Comment by KELSEYDOWLING7** [comment] 2024-04-12 16:25
Jake and I are pushing these updates into automation this afternoon

**Closed as completed by KELSEYDOWLING7** 2024-04-12 16:25 UTC
Labels: bug
