### ISSUE TITLE
HP phone call pilot expansion

### ISSUE THREAD

**Issue by mnataraj92** [Analyticsphere/metricsReportsRequests#121] opened 2024-02-06 20:03 UTC
@KELSEYDOWLING7 

The requirements as asked for in the initial pilot are:
Site (d_827220437)= HP (531629870) AND
Verification Status (d_821247024) = Verified (197316935) AND
Has one or more of survey modules 1-4 (d_949302066, d_536735468, d_976570371, d_663265240) not submitted (NE 231311385) AND
Has any baseline blood collected (d_878865966 = 353358909) (let’s not take into account urine or mouthwash this time around, just blood) AND
Not refused baseline survey (d_685002411_d_994064239 = 104430631) AND
Not refused all study activities (d_906417725 = 104430631) AND
Not withdrawn (d_747006172 = 104430631) AND
Not deceased (d_987563196 = 104430631)
 
Please output into an excel or CSV file the list to include: Connect ID, Study ID, and the number of survey reminders they have received (you probably need to derive this and you can base it on the work we did below to define what the message IDs of the survey reminders are in the Notifications table).

Additionally:
List includes those who have never taken a baseline module (@brotzmanmj, please indicate in the issue whether you want only those who have never taken a baseline module or if you want to the composition to be what it was last time plus those who never took a baseline module).

List excludes those who were called in the initial pilot. (List provided by HP)

**Comment by mnataraj92** [comment] 2024-02-06 21:22
2/6/24 Call with Madhuri and Michelle:

Suggestion:
1. Generate the whole list and not exclude anyone. Put everyone that meets above criteria in the list. See how many people we get and make sure that it makes sense. 

2. Next, cross check them against the HP list and see how many HP people are still on this list (it should be that anyone who has completed all their surveys are no longer on Kelsey's list, and anyone who has one or more surveys not submitted should be on the list). 

3. Once we confirm this is correct, then we will generate a list that removes the people HP has already called. 

@KELSEYDOWLING7 please share this out when completed. Include the list of tokens and columns of all the data (survey status, verification status, site, refusals, # of contact attempts, etc) @mnataraj92 and Kelsey to review.

**Comment by mnataraj92** [comment] 2024-02-06 22:08
Hi @brotzmanmj should there be a timeframe for the data?

**Comment by brotzmanmj** [comment] 2024-02-06 22:11
@mnataraj92 No, I don't think we limited it. I do know that we ran some descriptive stats on the list Kelsey generated to find out the distribution of number of months since biospeicmen collection and a few other descriptive items. You'll see them at the beginning of the original email thread. I suggest we run those again and take a look at them.

**Comment by KELSEYDOWLING7** [comment] 2024-02-07 15:19
[HP-Call-Expansion.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14195632/HP-Call-Expansion.pdf)
[HP_CallExpansion_Everyone.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/14195638/HP_CallExpansion_Everyone.csv)
[HP_LeftToCall.csv](https://github.com/Analyticsphere/metricsReportsRequests/files/14210678/HP_LeftToCall.csv)



@mnataraj92  Please let me know how this looks. For easier comparison I've separated number 1 above to be the "HP_CallExpansion_Everyone" csv and number 2 to be the "HP_LeftToCall" csv. The pdf contains the two descriptive stats Michelle mentioned above. 


Please note for the months since Biospecimen collection, I have confirmed there are no clinical blood collections for this group. That being said, whether we used the research blood collection variable d_173836415_d_266600170_d_561681068 or the research blood collection variable d_678166505 we get the same results, and 7 people who have blood collected are missing a blood collection time stamp. I have confirmed their  collections are finalized. These CIDs are:  "6909588989" "5100259491" "8766431369" "1953516116" "6290315884" "1509723644" "7862802323".

**Comment by mnataraj92** [comment] 2024-02-13 14:48
Thanks @KELSEYDOWLING7 ! For the date/time clinical blood collected, please use d_173836415_d_266600170_d_982213346. Those 7 CIDs should have a date/time associated with their blood collection. For research blood collected date/time please use d_173. 836415_d_266600170_d_561681068

@brotzmanmj I messaged you on teams yesterday but just for documentation purposes:
I ran the HP data in SAS with the conditions posted in this issue and I ended up with the same list of study IDs as Kelsey (except my list had 2 additional study ids). She re-ran her list and it matched mine, so 2 people must have recently been verified and not completed all 4 modules. 
 
I then compared my/Kelsey's list with the original list that HP sent, and created a separate list after removing the Connect IDs that showed up on both lists. After removing the studyids that showed up on both HP's list and my/Kelsey's list, there are 158 studyids left in my/Kelsey's list. 

@KELSEYDOWLING7 I'm uploading the excel file here. The first tab shows the comparison between the study ids from my list and your list based on all of the conditions above (with the 2 additional study ids on my list from before you re-ran yours). The overlap is indicated in red. The second tab shows our list compared with HPs list. The overlap is indicated in red. The third tab is the list that results from removing that overlap between our list and HP's list. There are 158 study ids. 

Could you please generate some basic frequencies of the list of 158 people, similar to the ones in the email thread where these requirements were documented?

**Comment by mnataraj92** [comment] 2024-02-13 15:23
Update: Kelsey re-ran the list and there are now 175 people (17 more people recently got verified from when this list was last run last week and have one or more modules not completed)

**Comment by brotzmanmj** [comment] 2024-02-13 15:25
And all of the people have done their biospecimen collection? Even the 17 who got verified last week?

**Comment by mnataraj92** [comment] 2024-02-13 15:29
@brotzmanmj Sorry! I think I accidentally deleted your comment; my github froze when I was editing my comment. Documenting it here:

I mentioned that Kelsey reran the #s and got 175 for the list (17 additional people that were verified from when this list was last ran). Michelle asked:  "And all of the people have done their biospecimen collection? Even the 17 who got verified last week?"

@mnataraj92 I'm going to rerun the list to see how many individuals I get that meet the above conditions and remove the duplicates between mine and HP's list.

**Comment by brotzmanmj** [comment] 2024-02-13 15:31
@mnataraj92  Thank you. And before you remove the duplicates, can you resend the file as is but include all of the variables that are part of the selection criteria?

**Comment by mnataraj92** [comment] 2024-02-13 15:33
sure!

**Comment by mnataraj92** [comment] 2024-02-13 16:36
@brotzmanmj here is the file with all variables included from the selection criteria: https://nih.app.box.com/file/1443477397700

The first tab is all of the data.

The second tab is comparing my list of study IDs with HP's list of study IDs. The red indicates overlap. 

The third tab (people not called) is my list of study IDs after removing the overlap with HP's list. There are 160 individuals- 2 more individuals from last week that were verified and met the remaining criteria. 

The fourth tab (people not called) is a list of 15 people (after removing duplicates from HP's list) that also meet the above criteria, but do not have a study ID. 

Therefore, there are a total of 175 participants meeting the above criteria after removing those in HP's list.  

@KELSEYDOWLING7 Could you please generate some basic frequencies of the list of the 175 people, similar to the ones in the email thread where these requirements were documented?

**Comment by KELSEYDOWLING7** [comment] 2024-02-13 17:02
@brotzmanmj Madhuri and I confirmed we have the same numbers now, the 175 remaining matches. When I ran it last week I had 171. Github is showing "commented last week" so I don't have the exact date I uploaded my last list, but there are 11 people that match this criteria that have had their BL blood drawn since last Monday, so that increase does make sense. 

Here are the two tables on those 175 people:
[HP-Call-Expansion.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14269716/HP-Call-Expansion.pdf)

**Comment by brotzmanmj** [comment] 2024-02-13 18:21
Thanks @KELSEYDOWLING7 can you send the rest of the tables?

**Comment by brotzmanmj** [comment] 2024-02-13 18:37
I primarily need a table of how many of the 4 baseline modules have they completed, and separately a table of how many BL survey emails have they been sent (including the first one that is the 'welcome to connect' that everyone gets).

**Comment by KELSEYDOWLING7** [comment] 2024-02-13 20:43
@brotzmanmj  Yes, here are the additional frequency tables. I also updated the footnotes to clarify that this is now frequencies of those left to call only 

[HP-Call-Expansion.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14271903/HP-Call-Expansion.pdf)

**Comment by brotzmanmj** [comment] 2024-02-14 15:28
Hi @KELSEYDOWLING7  the data on Last Survey Reminder Contact Attempt can't be right, in the table or in the CSV, they both look impossible. Can you take another look?

**Comment by brotzmanmj** [comment] 2024-02-14 15:30
And also after you figure out what's wrong with the contact attempts, can you add the blood collection date to the CSV file, and add a table to the pdf that indicates which survey modules they have completed? None, Module 1 only, or Module 1 plus another module? Thanks.

**Comment by KELSEYDOWLING7** [comment] 2024-02-14 16:07
@brotzmanmj  I will relook at the attempt counts. Can you clarify what makes the attempts not possible?



For the tables would you prefer this first option, where I could use this set up for Table 4 to replace Table 3?
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/c8067c59-1374-4e9b-b9f4-3608ce8a7f63)


Or specify which combination of modules they've completed?
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/9c3e27e7-49b3-496d-bc00-73073d5f8b83)

**Comment by brotzmanmj** [comment] 2024-02-14 16:12
Hi @KELSEYDOWLING7  the first option is good thanks

**Comment by KELSEYDOWLING7** [comment] 2024-02-14 16:18
@brotzmanmj  Ok will do. Can you clarify what makes the attempts not possible? Those are the counts I'm getting with several methods

**Comment by brotzmanmj** [comment] 2024-02-14 16:29
@KELSEYDOWLING7 what gave me an indication that something was not right at a glance was that some of the people with Last Survey Reminder Attempt = Contact Attempt 1  according to the csv file completed module 1 (only module 1) back in Nov 2023. That time gap means they should have gotten more reminders since then. So I looked one up in the SMDB, Connect ID 1437150315, and I see that person got all 6 baseline survey email reminders.

**Comment by brotzmanmj** [comment] 2024-02-14 16:30
And also please check the table in the pdf for Last Survey Reminder that has the 175 people listed. The way the frequencies are listed can't be right. It has all 175 have last survey reminder = 1st attempt, but there are only 175 people in the list total, so that can't be right.

**Comment by KELSEYDOWLING7** [comment] 2024-02-14 16:35
@brotzmanmj  Yes, that makes sense. Sorry the CSV I need to update so that only the last contact is shown.

For the table I can see where I made it confusing. I can keep the table as is but change the column name and title to reflect that these are the counts for each attempt, meaning all 175 received contact 1, 163 of the 175 received contact 2, ect. I would also need to check if this expanded time frame have any back posted notification.

OR I can either change the counts to only show the latest contact (how many people have received 1,2,3,4,5, or 6 TOTAL contacts), which is what the table title and column name implies now. Please let me know the preference and I'll update that right away

**Comment by brotzmanmj** [comment] 2024-02-14 16:43
The latest contact would be good, so that the CSV data and the table can be interpreted together. 
In fact, that's a good way for you to cross check and make sure the data look coherent.

**Comment by KELSEYDOWLING7** [comment] 2024-02-14 19:57
Perfect. This has been rerun and Madhuri and I spot checked in both BQ and the SMDB. The csv files have been updated with the correct Last Survey Attempt (only counting up to 6 attempts as discussed early on) and the time of biospecimen collection added. The csv's are located here: https://nih.app.box.com/folder/249014135080

And the tables have been updated accordingly:
[HP-Call-Expansion.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14285419/HP-Call-Expansion.pdf)

**Comment by brotzmanmj** [comment] 2024-02-14 20:10
Ok one last change, for this request I need the number of contacts through 10, not stopping at 6 attempts, because HP can only call if they have less than 10 attempts already. if they had 9 attempts they can make one phone call, if they have 8 or fewer they can make two calls. So can you remove that limitation and then hopefully we are done.

**Comment by KELSEYDOWLING7** [comment] 2024-02-14 20:27
@brotzmanmj  Easy enough! CSV's updated at that link and tables updated below
[HP-Call-Expansion.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14285741/HP-Call-Expansion.pdf)

**Comment by brotzmanmj** [comment] 2024-02-14 20:43
Looks good, thank you! I will move this forward to NORC and HP.

**Comment by KELSEYDOWLING7** [comment] 2024-02-14 20:51
@brotzmanmj  Great!! Glad to hear it

**Comment by mnataraj92** [comment] 2024-02-14 21:29
Great! Can I close this issue?

**Comment by brotzmanmj** [comment] 2024-02-14 21:49
yes thanks

**Closed as completed** 2024-02-14 22:02 UTC
Labels: Ad hoc

**Comment by brotzmanmj** [comment] 2024-02-15 13:50
@KELSEYDOWLING7 @mnataraj92  For informational purposes: HP has agreed to call the 115 individuals from this list with Module 1 = not started or started (not submitted). I downloaded the file and removed the 60 people who have submitted Module 1 and am providing the remaining list of 115 to NORC https://nih.app.box.com/file/1445447627993 to flag anyone who has a known technical issue.

**Comment by brotzmanmj** [comment] 2024-02-16 20:48
Update: NORC has reviewed the list and identified 6 cases with known technical issue. The list returned from NORC is here. https://nih.app.box.com/file/1446778278693 
First tab has 109 people with no CSC ticket (115 - 6)
Second tab has the list of the 6 people with CSC tickets, and third table explains what the CSC issue(s) were for those 6

I will upload the list to HP in their folder where they can access it
